### ISSUE TITLE
Archlinux PKGBUILDS out of date .

### ISSUE THREAD

**Issue by ghost** [rilian-la-te/vala-project-packages#22]
Can you update the archlinux pkgbuilds becouse they are out of date . Or if you don't have time to update them regularly you can add me as a co-mainter in aur so I can update them .

**Comment by rilian-la-te** [comment]
I will update sntray. But why git PKGBUILDS should be updated? AFAIK, makepkg can fetch latest version from repo.

**Comment by rilian-la-te** [comment]
git version of [vala-panel-sntray](https://aur.archlinux.org/packages/vala-panel-sntray-git/) is done. Do another packages needs updating for you?

**Comment by ghost** [comment]
i wasn't talking about the git versions . I did not notice there were git versions . I was talking about the pkgs that download the src from github releases page . Usualy people try to compile those from releases since it is considered more stable than upstream .

**Comment by rilian-la-te** [comment]
Now all packages are git versions:-)))

**Comment by rilian-la-te** [comment]
Feel free to create a non-git package:-)))

**Comment by ghost** [comment]
I don't know why we can't understand each other :D . But that wasn't  wath i was thinking of . They should have retained their release type pkbuild but should be frequently updated.

**Comment by rilian-la-te** [comment]
I does not have a release PKGBUILDs now. All is git. If you want release PKGBUILDs - feel free to create and maintain it. For me it is pain:-(

**Comment by ghost** [comment]
Yes it is . Now people won't get confused . Thank you .
