### ISSUE TITLE
debian budgie-appmenu installs to the wrong location

### ISSUE THREAD

**Issue by fossfreedom** [rilian-la-te/vala-project-packages#3]
ok - at the moment the budgie-appmenu installs itself to a multiarch location.  This will not work for budgie-desktop

i.e. /usr/lib/x86.../budgie-desktop/plugins/appmenu-budgie.plugin and libappmenu-budgie.so

it needs to be installed into its own subfolder under /usr/lib/budgie-desktop/plugins

i.e. /usr/lib/budgie-desktop/plugins/appmenu-budgie/

maybe some sort of debian .links type manipulation is required here.

**Comment by rilian-la-te** [comment]
try to modify -DCMAKE_INSTALL_LIBEXECDIR

**Comment by rilian-la-te** [comment]
And submit a PR. I do not have a debian distro now.
