### ISSUE TITLE
conflicts

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/vala-project-packages#5]
/usr/libexec/budgie-desktop/plugins/libappmenu-budgie.so exists in both 'vala-panel-appmenu-mate-git' and 'vala-panel-appmenu-xfce-git'
/usr/libexec/mate-panel/appmenu-mate exists in both 'vala-panel-appmenu-mate-git' and 'vala-panel-appmenu-xfce-git'
/usr/libexec/budgie-desktop/plugins/libappmenu-budgie.so exists in both 'vala-panel-appmenu-mate-git' and 'vala-panel-appmenu-valapanel-git'
/usr/libexec/mate-panel/appmenu-mate exists in both 'vala-panel-appmenu-mate-git' and 'vala-panel-appmenu-valapanel-git'
/usr/libexec/budgie-desktop/plugins/libappmenu-budgie.so exists in both 'vala-panel-appmenu-mate-git' and 'vala-panel-appmenu-budgie-git'
/usr/libexec/mate-panel/appmenu-mate exists in both 'vala-panel-appmenu-mate-git' and 'vala-panel-appmenu-budgie-git'
/usr/libexec/budgie-desktop/plugins/libappmenu-budgie.so exists in both 'vala-panel-appmenu-xfce-git' and 'vala-panel-appmenu-valapanel-git'
/usr/libexec/mate-panel/appmenu-mate exists in both 'vala-panel-appmenu-xfce-git' and 'vala-panel-appmenu-valapanel-git'
/usr/libexec/budgie-desktop/plugins/libappmenu-budgie.so exists in both 'vala-panel-appmenu-xfce-git' and 'vala-panel-appmenu-budgie-git'
/usr/libexec/mate-panel/appmenu-mate exists in both 'vala-panel-appmenu-xfce-git' and 'vala-panel-appmenu-budgie-git'
/usr/libexec/budgie-desktop/plugins/libappmenu-budgie.so exists in both 'vala-panel-appmenu-valapanel-git' and 'vala-panel-appmenu-budgie-git'
/usr/libexec/mate-panel/appmenu-mate exists in both 'vala-panel-appmenu-valapanel-git' and 'vala-panel-appmenu-budgie-git'
vala-panel-appmenu-budgie-git: /usr/lib/budgie-desktop/plugins/appmenu-budgie.plugin exists in filesystem
Errors occurred, no packages were upgraded.

**Comment by rilian-la-te** [comment]
I fixed this a hour ago into ArchLinux AUR and here. Try latest, please.

**Comment by SolarAquarion** [comment]
i have more conflicts 

/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'sntray-plugin-translations' and 'mate-panel-sntray'
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'sntray-plugin-translations' and 'xfce4-panel-sntray'
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'sntray-plugin-translations' and 'vala-panel-sntray'
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'sntray-plugin-translations' and 'budgie-sntray'
sntray-plugin-translations: /usr/share/glib-2.0/schemas/org.valapanel.toplevel.sntray.gschema.xml exists in filesystem
sntray-plugin-translations: /usr/share/locale/en_AU/LC_MESSAGES/xfce4-sntray-plugin.mo exists in filesystem
sntray-plugin-translations: /usr/share/locale/en_CA/LC_MESSAGES/xfce4-sntray-plugin.mo exists in filesystem
sntray-plugin-translations: /usr/share/locale/en_GB/LC_MESSAGES/xfce4-sntray-plugin.mo exists in filesystem
sntray-plugin-translations: /usr/share/locale/ie/LC_MESSAGES/xfce4-sntray-plugin.mo exists in filesystem
sntray-plugin-translations: /usr/share/locale/mo/LC_MESSAGES/xfce4-sntray-plugin.mo exists in filesystem
sntray-plugin-translations: /usr/share/locale/rue/LC_MESSAGES/xfce4-sntray-plugin.mo exists in filesystem
sntray-plugin-translations: /usr/share/locale/sma/LC_MESSAGES/xfce4-sntray-plugin.mo exists in filesystem
/usr/libexec/mate-panel/sntray-mate exists in both 'mate-panel-sntray' and 'xfce4-panel-sntray'
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'mate-panel-sntray' and 'xfce4-panel-sntray'
/usr/libexec/mate-panel/sntray-mate exists in both 'mate-panel-sntray' and 'vala-panel-sntray'
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'mate-panel-sntray' and 'vala-panel-sntray'
/usr/libexec/mate-panel/sntray-mate exists in both 'mate-panel-sntray' and 'budgie-sntray'
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'mate-panel-sntray' and 'budgie-sntray'
mate-panel-sntray: /usr/share/mate-panel/applets/org.vala-panel.SNTray.mate-panel-applet exists in filesystem
/usr/libexec/mate-panel/sntray-mate exists in both 'xfce4-panel-sntray' and 'vala-panel-sntray'
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'xfce4-panel-sntray' and 'vala-panel-sntray'
/usr/libexec/mate-panel/sntray-mate exists in both 'xfce4-panel-sntray' and 'budgie-sntray'
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'xfce4-panel-sntray' and 'budgie-sntray'
xfce4-panel-sntray: /usr/lib/xfce4/panel/plugins/libsntray-xfce.so exists in filesystem
xfce4-panel-sntray: /usr/share/xfce4/panel/plugins/sntray.desktop exists in filesystem
/usr/libexec/mate-panel/sntray-mate exists in both 'vala-panel-sntray' and 'budgie-sntray'
/usr/share/dbus-1/services/org.mate.panel.applet.SNTrayAppletFactory.service exists in both 'vala-panel-sntray' and 'budgie-sntray'
vala-panel-sntray: /usr/lib/vala-panel/applets/libsntray-valapanel.so exists in filesystem
vala-panel-sntray: /usr/lib/vala-panel/applets/sntray.plugin exists in filesystem
budgie-sntray: /usr/lib/budgie-desktop/plugins/libsntray-budgie.so exists in filesystem
budgie-sntray: /usr/lib/budgie-desktop/plugins/sntray-budgie.plugin exists in filesystem
Errors occurred, no packages were upgraded.

**Comment by rilian-la-te** [comment]
Above conflicts are fixed (with libexec)?

**Comment by rilian-la-te** [comment]
What package version are you trying to build?

**Comment by SolarAquarion** [comment]
yes, the libexec ones are fixed, the sntray ones are the ones with the
conflicts

**Comment by rilian-la-te** [comment]
Try release 3 from AUR

**Comment by rilian-la-te** [comment]
About conflicts with ```exists in filesystem``` - this is not PM issues, but `make install` artifacts. Just `rm -rf` it and try again.

**Comment by SolarAquarion** [comment]
I just did a makepkg -rsciC and sudo pacman -U *.pkg.* --force
