### ISSUE TITLE
vala-panel FTBFS on Ubuntu

### ISSUE THREAD

**Issue by flexiondotorg** [rilian-la-te/vala-project-packages#8]
I've started updating the packaging for `vala-panel` but it FTBFS when submitted to a PPA. It is late here and I can't spot this issue, here is the build log:

  * https://launchpadlibrarian.net/319631566/buildlog_ubuntu-artful-amd64.vala-panel_0.3.62-1~artful1.1_BUILDING.txt.gz

Any guidance appreciated. You can find my work-in-progress changes here:

  * https://github.com/flexiondotorg/vala-project-packages/tree/master/debian/vala-panel/debian

**Comment by rilian-la-te** [comment]
Do you using release tarball or latest master?

**Comment by flexiondotorg** [comment]
I'm using the 0.3.62 release tarball.

**Comment by rilian-la-te** [comment]
This is for vala-panel, not for menu:-)
I am asking about menu version.

**Comment by flexiondotorg** [comment]
What menu are you referring to?

**Comment by rilian-la-te** [comment]
This repository. Are you generate tarball yourself from master, or take 0.4.4 stock?

**Comment by rilian-la-te** [comment]
Sorry, confused with appmenu. Will look into vala-panel closer.

**Comment by rilian-la-te** [comment]
Try 0.3.63 alpha, please:)))

**Comment by flexiondotorg** [comment]
Thanks. It builds :-)

**Comment by rilian-la-te** [comment]
@flexiondotorg will you package xfce4-sntray-plugin and extras?
